name: Every day Run Python Script

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3:00 AM (night)



jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python main.py

      - name: Configure Git
        run: |
          git config --global user.name "Saule097"
          git config --global user.email "saule.kerimkulova@aigp.kz"

      - name: Commit CSV file
        run: |
          git add products.csv  # Replace 'products.csv' with the name of your CSV file
          git commit -m "Add generated CSV file"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Required for pushing changes

